#!/bin/bash
set -euo pipefail

# Optional helper to run the db_visualizer tool.
# This script is NOT invoked by startup.sh. It is for manual use only.
# It:
#  - changes into the correct working directory
#  - verifies Node.js and npm availability (exits 0 if missing)
#  - installs dependencies if missing
#  - detects and repairs a corrupted Express install (e.g., missing lib/express.js)
#  - starts the visualizer server

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VIS_DIR="${SCRIPT_DIR}/db_visualizer"

if [ ! -d "${VIS_DIR}" ]; then
  echo "db_visualizer directory not found at ${VIS_DIR}"
  exit 1
fi

cd "${VIS_DIR}"

# Ensure Node/npm exist
if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
  echo "Node.js (v18+) and npm are required to run the db_visualizer."
  echo "Skipping visualizer start. PostgreSQL remains unaffected."
  exit 0
fi

# Helper: install deps cleanly in the correct folder (preserve lockfile if present)
install_deps() {
  echo "Installing db_visualizer dependencies..."
  rm -rf node_modules 2>/dev/null || true
  if [ -f "package-lock.json" ]; then
    npm ci --no-audit --no-fund || npm install --no-audit --no-fund
  else
    npm install --no-audit --no-fund
  fi
}

# Helper: perform a clean reinstall (nuke node_modules and lockfile)
reinstall_clean() {
  echo "Performing clean reinstall (removing node_modules and package-lock.json)..."
  rm -rf node_modules package-lock.json 2>/dev/null || true
  npm install --no-audit --no-fund
}

# Verify express module can be resolved and not corrupted
verify_express_integrity() {
  local resolved
  resolved="$(node -p "require.resolve('express')" 2>/dev/null || echo "")"
  if [ -z "${resolved}" ]; then
    # Not resolvable
    return 1
  fi
  local dir
  dir="$(dirname "${resolved}")"
  # Express v4 uses index.js -> ./lib/express; ensure lib exists
  if [ ! -f "${dir}/lib/express.js" ]; then
    return 1
  fi
  return 0
}

NEED_INSTALL=0
NEED_CLEAN=0

# Decide if we need install or clean reinstall
if [ ! -d "node_modules" ]; then
  NEED_INSTALL=1
else
  # Try resolving express
  if ! node -e "require.resolve('express');" >/dev/null 2>&1; then
    NEED_INSTALL=1
  else
    # Resolve succeeded; check for corruption (missing lib/express.js)
    if ! verify_express_integrity; then
      NEED_CLEAN=1
    fi
  fi
fi

if [ "${NEED_INSTALL}" -eq 1 ]; then
  install_deps
fi

if [ "${NEED_CLEAN}" -eq 1 ]; then
  echo "Detected corrupted Express installation (likely missing lib/express.js)."
  reinstall_clean
fi

# Final verification after any install/repair
if ! node -e "require.resolve('express');" >/dev/null 2>&1 || ! verify_express_integrity; then
  echo "Failed to resolve a valid 'express' installation after dependency setup."
  echo "Please check network access or npm registry and try again."
  exit 1
fi

# Load Postgres env if file exists (generated by startup.sh)
if [ -f "postgres.env" ]; then
  # shellcheck disable=SC1091
  source "postgres.env"
fi

echo "Starting db_visualizer on http://localhost:3000 ..."
npm start --silent
