#!/bin/bash
set -euo pipefail

# Optional helper to run the db_visualizer tool.
# This script is NOT invoked by startup.sh. It is for manual use only.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VIS_DIR="${SCRIPT_DIR}/db_visualizer"

if [ ! -d "${VIS_DIR}" ]; then
  echo "db_visualizer directory not found at ${VIS_DIR}"
  exit 1
fi

cd "${VIS_DIR}"

# Ensure Node/npm exist
if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
  echo "Node.js (v18+) and npm are required to run the db_visualizer."
  echo "Skipping visualizer start. PostgreSQL remains unaffected."
  exit 0
fi

# Helper: install deps cleanly in the correct folder
install_deps() {
  echo "Installing db_visualizer dependencies..."
  rm -rf node_modules 2>/dev/null || true
  # Prefer reproducible install when lockfile exists
  if [ -f "package-lock.json" ]; then
    npm ci --no-audit --no-fund || npm install --no-audit --no-fund
  else
    npm install --no-audit --no-fund
  fi
}

# If node_modules missing or express cannot be resolved, (re)install
NEED_INSTALL=0
if [ ! -d "node_modules" ]; then
  NEED_INSTALL=1
else
  node -e "require.resolve('express');" >/dev/null 2>&1 || NEED_INSTALL=1
fi

if [ "$NEED_INSTALL" -eq 1 ]; then
  install_deps
  # Verify express resolved
  if ! node -e "require.resolve('express');" >/dev/null 2>&1; then
    echo "Failed to resolve 'express' after install. Please check network access or npm registry."
    exit 1
  fi
fi

# Load Postgres env if file exists (generated by startup.sh)
if [ -f "postgres.env" ]; then
  # shellcheck disable=SC1091
  source "postgres.env"
fi

echo "Starting db_visualizer on http://localhost:3000 ..."
npm start --silent
