#!/bin/bash
set -euo pipefail

# Optional helper to run the db_visualizer tool.
# This script is NOT invoked by startup.sh. It is for manual use only.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VIS_DIR="${SCRIPT_DIR}/db_visualizer"

if [ ! -d "${VIS_DIR}" ]; then
  echo "db_visualizer directory not found at ${VIS_DIR}"
  exit 1
fi

cd "${VIS_DIR}"

# If node_modules is missing, install dependencies
if [ ! -d "node_modules" ]; then
  echo "Installing db_visualizer dependencies..."
  if command -v npm >/dev/null 2>&1; then
    # Try npm ci first if lockfile exists; fallback to npm install
    if [ -f "package-lock.json" ]; then
      npm ci --no-audit --no-fund || npm install --no-audit --no-fund
    else
      npm install --no-audit --no-fund
    fi
  else
    echo "npm is not installed. Please install Node.js (v18+) and npm."
    exit 1
  fi
fi

# Load Postgres env if file exists (generated by startup.sh)
if [ -f "postgres.env" ]; then
  # shellcheck disable=SC1091
  source "postgres.env"
fi

echo "Starting db_visualizer on http://localhost:3000 ..."
npm start --silent
