-- Career Platform Database - Reference Schema (PostgreSQL)
-- This schema aligns with the MVP backend models for Users, Roles, Competencies,
-- Role-Competency mapping, and Role Adjacency. It uses TEXT primary keys which
-- are compatible with UUIDv4 strings generated by the application layer.
-- Apply using:
--   psql -h localhost -U appuser -d myapp -p 5001 -f schema.sql

BEGIN;

-- USERS: core user record; roles are attached via user_roles join table.
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ROLES: role definitions (metadata stores arbitrary JSON).
CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  metadata JSONB,
  version TEXT,
  source TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- USER_ROLES: many-to-many between users and roles.
CREATE TABLE IF NOT EXISTS user_roles (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, role_id)
);

-- COMPETENCIES: reusable capabilities/skills.
CREATE TABLE IF NOT EXISTS competencies (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  definition TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ROLE_COMPETENCIES: required competencies for a role.
-- required_level is free-text to allow scale variations (e.g., Beginner/Intermediate/Advanced/Expert).
CREATE TABLE IF NOT EXISTS role_competencies (
  id TEXT PRIMARY KEY,
  role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  competency_id TEXT NOT NULL REFERENCES competencies(id) ON DELETE CASCADE,
  required_level TEXT,
  weight NUMERIC(6,3) DEFAULT 1.000,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (role_id, competency_id)
);

-- ROLE_ADJACENCY: directional adjacency/relatedness between roles (0..1).
CREATE TABLE IF NOT EXISTS role_adjacency (
  id TEXT PRIMARY KEY,
  source_role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  target_role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  score NUMERIC(6,3) NOT NULL DEFAULT 0.000,
  rationale TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source_role_id, target_role_id),
  CONSTRAINT different_roles CHECK (source_role_id <> target_role_id),
  CONSTRAINT score_range CHECK (score >= 0.0 AND score <= 1.0)
);

-- Helpful indexes for case-insensitive search and joins.
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users (LOWER(email));
CREATE INDEX IF NOT EXISTS idx_roles_name_lower ON roles (LOWER(name));
CREATE INDEX IF NOT EXISTS idx_competencies_name_lower ON competencies (LOWER(name));
CREATE INDEX IF NOT EXISTS idx_role_comp_role ON role_competencies (role_id);
CREATE INDEX IF NOT EXISTS idx_role_comp_comp ON role_competencies (competency_id);
CREATE INDEX IF NOT EXISTS idx_role_adj_src ON role_adjacency (source_role_id);
CREATE INDEX IF NOT EXISTS idx_role_adj_tgt ON role_adjacency (target_role_id);

COMMIT;

-- Notes:
-- - IDs are TEXT to support application-generated UUID strings across engines (SQLite, Postgres).
-- - Consider adding RLS, audit logs, and templates in future iterations per platform compliance needs.
